//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBT.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAnswer
    {
        public int Id { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public string Answer { get; set; }
        public Nullable<bool> IsCorrect { get; set; }
        public Nullable<decimal> PrecisionLevel { get; set; }
        public Nullable<int> StudentExamNo { get; set; }
        public Nullable<decimal> Score { get; set; }
    
        public virtual ExamQuestion ExamQuestion { get; set; }
        public virtual Student Student { get; set; }
        public virtual StudentExam StudentExam { get; set; }
    }
}
