//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBT.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentExam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentExam()
        {
            this.StudentAnswers = new HashSet<StudentAnswer>();
        }
    
        public int ID { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> ExamId { get; set; }
    
        public virtual Exam Exam { get; set; }
        public virtual Student Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentAnswer> StudentAnswers { get; set; }
    }
}
